### PR TITLE
Add support for HSTS preload and includeSubDomains directives 

### PR DESCRIPTION
**Pull request by dboehmer**
This is based on #3 but adds additional feature. So I made another PR.

### CODE REVIEW

**Comment by ap** [comment]
Hi, thank you for the patches. I’ll get back to you once I’ve taken a look at the new headers, so I can decide whether to merge this as is.

**Comment by dboehmer** [comment]
@ap Are you currently working on this or shall I upload a rebased version of this branch?

**Comment by ap** [comment]
Loose code review thoughts so far:

* Validating the values on *every single request* is not the best way to go about this. I’m thinking along the lines of rendering the STS header value to a private attribute in `prepare_app`.

* Refusing to work until the user sets all of the right values is not great UI. If the user asks for contradictory things, sure, can’t do that, but if they have not, and the  computer knows what the user wants, it should generally just do it. The defaults of different options should accommodate each others’ different requirements. If the user asks for `preload`, then `max-age` should either change default to something sensible for that case or should have no default for that case (i.e. throw an error if not explicitly set). But sticking with the usual default value even though that will lead to errors from another option is… not the best way to go.

* Not yet sure how I feel about the three separate options for HSTS. It may make more sense to have a single option that can take a hashref. Or maybe three separate options do make the most sense. Or maybe something else. I don’t have a good sense of this yet.

Stepping back a bit after the last item, though… maybe the module should not be in the business of forever adding support for every variation of the header now and in the future. Maybe it should allow just the user to make the header value anything they want, and merely offer convenience shortcuts for the most common use cases. Or maybe not. I have to chew on this one a bit.

(In the limit, you can always use Plack::Middleware::Rewrite (or just a custom middleware of your own) to do absolutely anything you want with a request or its response – you are not reliant solely on this or any other middleware for support of any HTTP feature.)

So… I’m afraid I won’t take these patches verbatim. Sorry for the bummer. I do appreciate you taking the time to write tests and docs, though. I’m not sure how the patch will ultimately look, but I’ll make sure to keep anything from your patches that still remains applicable.

**Comment by dboehmer** [comment]
1. Doing validation just once is a really good point. I just extended the code as it is.

2. I think the plugin code *does* work regardless if the config values make sense or not. But HSTS preload won't work. It would be a good idea to let `includeSubDomains` default to true if not defined but `preload` is enabled. For HSTS preload the default `max-age` should be 1 year but I didn't dare to change the default value because this will alter actual deployments. How to resolve this?

3. I also think it's not the nicest solution. I was working on a new plugin for the Catalyst framework for HSTS before I discovered your module by chance. My config schema was like this: the Catalyst app needs to load my plugin. It has it's own section in the app's config and works reasonably without any config. The plugin can be disabled all together with `disabled => 1`. For `max-age`, `preload` and `includeSubDomains` there are 3 keys. `max-age` is 1 year per default. `preload` is false. `includeSubDomains` is true if `preload` is enabled.

In the beginning I also thought this is just 1 line of code in Catalyst or Plack to add 1 other HTTP header but my experience convinced me it's more than that: You should only send HSTS over HTTPS and enabling `preload` has some requirements. I'd really like to see that implemented right once.

**Comment by ap** [comment]
> In the beginning I also thought this is just 1 line of code in Catalyst or Plack to add 1 other HTTP header but my experience convinced me it's more than that: You should only send HSTS over HTTPS and enabling `preload` has some requirements. I'd really like to see that implemented right once.

True, good point.

**Comment by ap** [comment]
I’m still thinking about the interface. In the meantime I’ve pushed [a `preload` branch](/ap/Plack-Middleware-RedirectSSL/tree/preload) that so far just allows the user to specify an arbitrary HSTS header. That feels like probably the right direction for fitting the feature into the existing API.

**Comment by ap** [comment]
I just updated [the `preload` branch](/ap/Plack-Middleware-RedirectSSL/tree/preload) with another iteration. It took a rather long time to get this right because of the stupid interface I designed originally. Sorry about that.

A reasonable but also convenient interface for comprehensive HSTS support took some puzzling out. In the end I decided that creating a policy through mutation is incompatible with intelligent defaulting logic, so a policy has to be passed as a whole.

But preserving backcompat faithfully while integrating the new interface while isolating the stupidity of the old one was the real headache. In the end I think I managed to preserve all invariants of the old interface to the extent that they’re meaningful – the most central ones being that `$redirssl->hsts` doesn’t suddenly start returning new kinds of values from one version to another, and that it does this while `$redirssl->hsts( $redirssl->hsts )` never surprises the user either. (That last bit of code is artificial but is a minimal reduction of larger actually-plausible code.)

Docs are completely absent as yet, and the beyond-`max-age` HSTS support is also entirely untested, but… feel free to take a look and give me any feedback you might have.

**Comment by ap** [comment]
I think the code and docs have settled, barring bugs/problems I didn’t realise yet because I have a bunch of tests for `render_sts_policy` left to write. But if writing those tests doesn’t turn up anything then the code will remain as it is now.

**Comment by ap** [comment]
OK, tests done too, nothing much changed. Branch updated.

@dboehmer: Are you still following along? Can you take a look at the branch and give me your thoughts?

**Comment by ap** [comment]
I lied about the tests – coverage was below 100%. That’s now fixed as well.

**Comment by ap** [comment]
Shipped 606e11b926a8d83b8ce8b068fe7549b858227078 as 1.300 to CPAN.

Share and enjoy. 😊

**Comment by dboehmer** [comment]
@ap: I am still following but didn't manage to look into the code before you released. I just went through the changes and it's more complex than I expected but it seems you really tried to do *the right thing*. Thank you for picking up my idea and building something complete!

**Comment by ap** [comment]
NP, and thank you for instigating the addition. And yeah I kicked myself quite a bit over my stupid, *stupid* original interface design. Not that this feature would necessarily have been *simple* in any case, but the legacy interface added unnecessary complexity and *a lot* of extra work to backtrack into the final design. Note to self, avoid making your APIs *too* cute and DWIMmy…

**Pull request closed without merging**
